---
applications:
- name: prometheus-exporter
  memory: 100M
  instances: 1
  buildpacks:
    - go_buildpack
  stack: cflinuxfs3
  env:
    GOPACKAGENAME: github.com/alphagov/paas-prometheus-exporter
