baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'CRED'


[menu]
  [[menu.main]]
    identifier = "publications"
    name = "Publications"
    url = "/publications/"

  [[menu.main]]
    identifier = "faqs"
    name = "FAQS"
    url = "/faqs/"