baseURL = 'https://cred-spontaneous-gerenuk-qq.london.cloudapps.digital/'
languageCode = 'en-us'
title = 'CRED Independent Commission'


[params]
favicon = "static/images/favicon.ico" # Path to favicon file
